---
servers:
  - name: compute1
    adapters:
      - endpoint_ports: ['eth1','eth2']
        switch_ports: ['Ethernet1','Ethernet1']
        switches: ['BA-Leaf1a','BA-Leaf1b']
        profile: compute
        validate_lldp: false
  - name: compute2
    adapters:
      - endpoint_ports: ['eth1']
        switch_ports: ['Ethernet1']
        switches: ['BA-MemberLeaf1']
        profile: client
        validate_lldp: false
