---
# link to docu: https://avd.sh/en/latest/roles/eos_designs/doc/connected-endpoints.html
port_profiles:
  - profile: hosting10
    mode: access
    vlans: "10"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: true
  - profile: hosting20
    mode: access
    vlans: "20"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: true
  - profile: hosting100
    mode: access
    vlans: "100"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: true
  - profile: hosting100_PO
    mode: access
    vlans: "100"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: true
    port_channel:
      mode: active
  - profile: hosting200
    mode: access
    vlans: "200"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: true
  - profile: hosting200_PO
    mode: access
    vlans: "200"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: true
    port_channel:
      mode: active
