---
port_profiles:
- mode: trunk
  profile: PP_TRUNK_EDGE
  spanning_tree_bpdufilter: false
  spanning_tree_bpduguard: true
  spanning_tree_portfast: edge
  storm_control: &id001 {}
- mode: access
  profile: PP_ACCESS_EDGE
  spanning_tree_bpdufilter: false
  spanning_tree_bpduguard: true
  spanning_tree_portfast: edge
  storm_control: *id001

- parent_profile: PP_TRUNK_EDGE
  profile: compute
  vlans: "10,20"

- parent_profile: PP_TRUNK_EDGE
  profile: client
  vlans: "10,20"