authoritative;
default-lease-time 600;
max-lease-time 7200;
subnet 172.100.36.0 netmask 255.255.255.0 {
  range 172.100.36.200 172.100.36.240;
  option routers 172.100.36.1;
  option domain-name-servers 8.8.8.8;
  option bootfile-name "http://172.100.36.253/bootstrap.py";

  host BA-Spine1 {
    hardware ethernet 00:1c:11:11:ba:01;
    option host-name "BA-Spine1";
  }
  host BA-Spine2 {
    hardware ethernet 00:1c:11:11:ba:02;
    option host-name "BA-Spine2";
  }
  host BA-Leaf1a {
    hardware ethernet 00:1c:11:11:ba:11;
    option host-name "BA-Leaf1a";
  }
  host BA-Leaf1b {
    hardware ethernet 00:1c:11:11:ba:12;
    option host-name "BA-Leaf1b";
  }
  host BA-MemeberLeaf1 {
    hardware ethernet 00:1c:11:11:ba:13;
    option host-name "BA-MemeberLeaf1";
  }
}

